# Generated by Django 3.0.7 on 2020-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav',
            field=models.IntegerField(default=0),
        ),
    ]
